# cd-adoagents-infra.yml
#
# Description: 
#   Provisions baseline infrastructure to support VM and VM Scale Set 
#   and image building operations. 

name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

parameters:
- name: whatifOperation
  displayName: 'Run "what-if" operation'
  type: boolean
  default: false

resources:
  pipelines:
  - pipeline: ci-adoagents-infra-resource
    source: ci-adoagents-infra

variables:
# Common config variables
- template: templates/variables-config-common.yml

# The template root path for the IaC templates
- name: templateRootPath
  value: $(Pipeline.Workspace)/ci-adoagents-infra-resource/drop-infra/iac

# The scripts root path for all the scripts
- name: scriptsRootPath
  value: $(Pipeline.Workspace)/ci-adoagents-infra-resource/drop-infra/scripts

# The full Bicep file path for provisioning the baseline infrastruture
- name: templateFilePath
  value: $(templateRootPath)/adoagents-infra.bicep

trigger: none

extends:
  template: templates/pipeline-adoagents-infra.yml
  parameters:
    sandboxSteps:
    - template: templates/steps-infra-adoagents.yml
      parameters:
        environmentType: sandbox
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        scriptsRootPath: '$(scriptsRootPath)'
        serviceConnectionName: 'agent-image-contoso-app-sbx'
        ${{ if eq(parameters.whatifOperation, true) }}:
          whatifOperation: 1
    productionSteps:
    - template: templates/steps-infra-adoagents.yml
      parameters:
        environmentType: production
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        scriptsRootPath: '$(scriptsRootPath)'
        serviceConnectionName: 'agent-image-contoso-app-prd'
        ${{ if eq(parameters.whatifOperation, true) }}:
          whatifOperation: 1