name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  pipelines:
  - pipeline: ci-infra-agents-resource
    source: ci-infra-agents

variables:
- template: templates/variables-common.yml
- name: templateRootPath
  value: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/iac/templates
- name: templateFilePath
  value: $(templateRootPath)/agents.bicep
- name: sandboxEnvironmentType
  value: sbx
- name: productionEnvironmentType
  value: prd

trigger: none

extends:
  template: templates/pipeline-infra-agents.yml
  parameters:
    sandboxSteps:
    - template: /.azure/pipelines/templates/steps-infra-agents.yml
      parameters:
        environmentType: sandbox
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        serviceConnectionName: agent-image-contoso-app-sbx
    productionSteps:
    - template: /.azure/pipelines/templates/steps-infra-agents.yml
      parameters:
        environmentType: production
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        serviceConnectionName: agent-image-contoso-app-sbx