name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  pipelines:
  - pipeline: ci-infra-agents-resource
    source: ci-infra-agents

variables:
- template: templates/variables-common.yml
- name: templateFilePath
  value: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/templates/images.bicep
- name: templateFileParameterPath
  value: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/templates/images.parameters.sbx.json
- name: location
  value: eastus2
  
trigger: none

stages:
- stage: infraDeploy
  displayName: Agent Infrastructure Build
  jobs:
  - deployment: provisionInfra
    displayName: Provision Infrastructure
    environment: 'pipeline-images-nonprod'
    strategy:
      runOnce:
        deploy:
          steps: 
          - checkout: self
          - task: AzureCLI@2
            name: provisionImageInfrastructure
            displayName: Provision Image Infrastructure
            inputs:
              azureSubscription: 'agent-image-contoso-app-sbx'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az group create \
                  --name "rg-$(organizationName)-images-sbx" \
                  --location "$(location)"
                az deployment group create \
                  --resource-group "rg-$(organizationName)-images-sbx" \
                  --template-file $(templateFilePath) \
                  --parameters $(templateFileParameterPath) \
                  --parameters organizationName=$(organizationName)

