name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  pipelines:
  - pipeline: ci-infra-agents-resource
    source: ci-infra-agents

variables:
- template: templates/variables-common.yml
- name: templateFilePath
  value: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/templates/images.bicep
- name: sandboxEnvironmentType
  value: sbx
- name: productionEnvironmentType
  value: prd

trigger: none

extends:
  template: templates/pipeline-infra-agents-images.yml
  parameters:
    sandboxSteps:
    - template: templates/steps-infra-agents-images.yml
      parameters:
        environmentType: $(sandboxEnvironmentType)
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        templateFileParameterPath: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/templates/images.parameters.$(sandboxEnvironmentType).json
    productionSteps:
    - template: templates/steps-infra-agents-images.yml
      parameters:
        environmentType: $(productionEnvironmentType)
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        templateFileParameterPath: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/templates/images.parameters.$(productionEnvironmentType).json
