name: $(Build.DefinitionName)-$(SourceBranchName)-$(versionSemantic)

resources:
  pipelines:
  - pipeline: ci-infra-agents-resource
    source: ci-infra-agents
    branch: main
    trigger: 
      branches: 
      - main

variables:
- template: templates/variables-imageinfra-sandbox.yml
  parameters:
    versionMajor: 1
    versionMinor: 0


trigger: none

stages:
- stage: infraDeploy
  displayName: Agent Infrastructure Build
  jobs:
  - deployment: provisionInfra
    displayName: Provision Infrastructure
    variables:
    - name: foo
      value: 'bar'
    environment: 'pipeline-images-nonprod'
    strategy:
      runonce:
        deploy:
          steps: 
          - checkout: self
          - task: AzureResourceGroupDeployment@2
            name: provisionImageInfrastructure
            displayName: Provision Image Infrastructure
            inputs:
              ConnectedServiceName: 'agent-image-contoso-app-sbx'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'rg-contoso-images-sbx'
              location: eastus2
              templateLocation: 'Linked artifact'
              csmFile: $(Pipeline.Workspace)/ci-infra-agents-resource/templates/images.bicep
              csmParametersFile: $(Pipeline.Workspace)/ci-infra-agents-resource/templates/images.parameters.sbx.json
              overrideParameters: >
                -storageName fabrikam
                -adminUsername $(vmusername)
                -adminPassword $(password)
              deploymentMode: Incremental
              deploymentGroupEndpoint: serviceconnectionname


contoso
agent
image 
'/.azure/pipelines/templates/variables-version-semantic.yml'

