# cd-infra-adoagents-infra.yml
#
# Description: 
#   Provisions baseline infrastructure to support VM and VM Scale Set 
#   and image building operations. 

name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  pipelines:
  - pipeline: ci-infra-adoagents-resource
    source: ci-infra-adoagents

variables:
# Common config variables
- template: templates/variables-config-common.yml

# The template root path for the IaC templates
- name: templateRootPath
  value: $(Pipeline.Workspace)/ci-infra-adoagents-resource/drop-infra/iac

# The scripts root path for all the scripts
- name: scriptsRootPath
  value: $(Pipeline.Workspace)/ci-infra-adoagents-resource/drop-infra/scripts

# The full Bicep file path for provisioning the baseline infrastruture
- name: templateFilePath
  value: $(templateRootPath)/adoagents-infra.bicep

trigger: none

extends:
  template: templates/pipeline-infra-adoagents.yml
  parameters:
    sandboxSteps:
    - template: templates/steps-infra-adoagents.yml
      parameters:
        environmentType: sandbox
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        scriptsRootPath: '$(scriptsRootPath)'
        serviceConnectionName: $(serviceConnection)
    productionSteps:
    - template: templates/steps-infra-adoagents.yml
      parameters:
        environmentType: production
        organizationName: $(organizationName)
        location: $(location)
        subscription: $(subscription)
        templateFilePath: $(templateFilePath)
        scriptsRootPath: '$(scriptsRootPath)'
        serviceConnectionName: $(serviceConnection)