name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  pipelines:
  - pipeline: ci-infra-agents-resource
    source: ci-infra-agents

variables:
- template: templates/variables-common.yml
- template: templates/variables-infra-agents-images-sbx.yml
- template: templates/variables-infra-agents-images-prd.yml
- name: templateFilePath
  value: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/templates/images.bicep
- name: templateFileParameterPath
  value: $(Pipeline.Workspace)/ci-infra-agents-resource/drop-infra/templates/images.parameters.sbx.json
- name: location
  value: eastus2
- name: sandboxEnvironmentType
  value: sbx
- name: productionEnvironmentType
  value: prd

trigger: none

extends:
  template: templates/pipeline-infra-agents-images.yml
  parameters:
    sandboxSteps:
    - checkout: self
    - task: AzureCLI@2
      name: provisionImageInfrastructure
      displayName: Provision Image Infrastructure
      inputs:
        azureSubscription: rg-$(organizationName)-images-$(sandboxEnvironmentType)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          organizationName=$1
          location=$2
          subscription=$3
          environmentType=$4
          templateFilePath=$5
          templateFileParameterPath=$6

          resourceGroupName="rg-$organizationName-images-$environmentType"

          organizationName
          az group create \
            --name $resourceGroupName \
            --location $location

          az tag create \
            --resource-id /subscriptions/$subscription/resourcegroups/$resourceGroupName \
            --tags envtype=$environmentType use=images org=$organizationName

          az deployment group create \
            --resource-group $resourceGroupName \
            --template-file $templateFilePath \
            --parameters $templateFileParameterPath \
            --parameters organizationName=$(organizationName)
        arguments: >
          $(organizationName)
          $(location)
          $(subscription)
          $(sandboxEnvironmentType)
          $(templateFilePath)
          $(templateFileParameterPath)

    productionSteps:
    - checkout: self
    - task: AzureCLI@2
      name: provisionImageInfrastructure
      displayName: Provision Image Infrastructure
      inputs:
        azureSubscription: rg-$(organizationName)-images-$(productionEnvironmentType)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          organizationName=$1
          location=$2
          subscription=$3
          environmentType=$4
          templateFilePath=$5
          templateFileParameterPath=$6

          resourceGroupName="rg-$organizationName-images-$environmentType"

          organizationName
          az group create \
            --name $resourceGroupName \
            --location $location

          az tag create \
            --resource-id /subscriptions/$subscription/resourcegroups/$resourceGroupName \
            --tags envtype=$environmentType use=images org=$organizationName

          az deployment group create \
            --resource-group $resourceGroupName \
            --template-file $templateFilePath \
            --parameters $templateFileParameterPath \
            --parameters organizationName=$(organizationName)
        arguments: >
          $(organizationName)
          $(location)
          $(subscription)
          $(productionEnvironmentType)
          $(templateFilePath)
          $(templateFileParameterPath)
