name: $(Build.DefinitionName)-$(SourceBranchName)-$(versionSemantic)

resources:
  pipelines:
  - pipeline: ci-infra-agents-resource
    source: ci-infra-agents
    branch: createagentinfrapipeline
    trigger: none

variables:
- template: templates/variables-common.yml

trigger: none

stages:
- stage: infraDeploy
  displayName: Agent Infrastructure Build
  jobs:
  - deployment: provisionInfra
    displayName: Provision Infrastructure
    variables:
    - name: foo
      value: 'bar'
    environment: 'pipeline-images-nonprod'
    strategy:
      runOnce:
        deploy:
          steps: 
          - checkout: self
          - task: AzureResourceGroupDeployment@2
            name: provisionImageInfrastructure
            displayName: Provision Image Infrastructure
            inputs:
              ConnectedServiceName: 'agent-image-$(organizationName)-app-sbx'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'rg-$(organizationName)-images-sbx'
              location: eastus2
              templateLocation: 'Linked artifact'
              csmFile: $(Pipeline.Workspace)/ci-infra-agents-resource/templates/images.bicep
              csmParametersFile: $(Pipeline.Workspace)/ci-infra-agents-resource/templates/images.parameters.sbx.json
              overrideParameters: >
                -organizationName $(organizationName)
              deploymentMode: Incremental

