name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-latest'
  
variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

schedules:
- cron: "0 0 * * 0"
  displayName: Sundays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    imageType: ubuntu2004
    vmSize: Standard_D4s_v4
    imageReadmeName: Ubuntu2004-README.md
    imageDefinitionName: 'ubuntu2004'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Ubuntu 2004.'
    imageOffer: 'DevOpsAgent'
    imageSku: 'Ubuntu2004HostedBaseline'
    imageOsType: 'Linux'
    publish: true
