name: $(Build.DefinitionName)-$(SourceBranchName)-$(versionSemantic)

variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - '/iac/*'

stages:
- stage: infraBuild
  displayName: Agent Infrastructure Build
  jobs:
  - job: buildInfrastructure
    displayName: Build Infrastructure Files
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1

    - task: PowerShell@2
      displayName: Build Bicep files
      inputs:
        targetType: 'inline'
        script: |
          az bicep version

          Get-ChildItem -Path .\ -Filter *.bicep -Recurse -File | ForEach-Object { 
            $bicepFilePath = $_.FullName 
            Write-Host "Building bicep file: $bicepFilePath"
            az bicep build --file $bicepFilePath
          }
        pwsh: true

    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop-infra
    - script: |
        echo "##vso[build.addbuildtag]infra"
        echo "##vso[build.addbuildtag]pipelineagents"
        echo "##vso[build.addbuildtag]$(versionSemantic)"
        echo "##vso[build.addbuildtag]build"
      displayName: Tag Build