name: $(Build.DefinitionName)-$(SourceBranchName)-$(versionSemantic)

variables:
- template: templates/variables-version-semantic.yml
- template: templates/variables-infra-agents-sbx.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - '/iac/*'

stages:

- stage: lint
  displayName: Lint
  jobs:
  - job: buildLintBicep
    displayName: Lint and Build Bicep Files
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1

    - task: PowerShell@2
      displayName: Validate Bicep Installation
      inputs:
        targetType: 'inline'
        script: |
          az bicep version
          if (0 -ne $LASTEXITCODE) {
            az bicep install
            if (0 -ne $LASTEXITCODE) {
              throw "Failed installing Azure Bicep CLI"
            }
          }
        pwsh: true

    - task: PowerShell@2
      displayName: Build Bicep files
      inputs:
        targetType: 'inline'
        script: |
          az bicep version

          Get-ChildItem -Path .\ -Filter *.bicep -Recurse -File | ForEach-Object { 
            $bicepFilePath = $_.FullName 
            # Build and lint the bicep file
            az bicep build --file $bicepFilePath
          }
        pwsh: true
        failOnStderr: true  # set to true to capture stderr bicep errors from linter

    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop-infra
    - script: |
        echo "##vso[build.addbuildtag]infra"
        echo "##vso[build.addbuildtag]pipelineagents"
        echo "##vso[build.addbuildtag]$(versionSemantic)"
        echo "##vso[build.addbuildtag]build"
      displayName: Tag Build

- stage: validate
  displayName: Validate
  jobs:
  - jobs: validateBicep
    displayName: Validate Bicep
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub validate \
            --name myMlzDeployment \
            --location $(location) \
            --template-file ./mlz.bicep

