name: $(Build.DefinitionName)-$(SourceBranchName)-$(versionSemantic)

variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - '/templates/*'
    - '/scripts/*'
    - '/.azure/pipelines/templates/variables-version-semantic.yml'

stages:
- stage: infraBuild
  displayName: Agent Infrastructure Build
  jobs:
  - job: copyInfra
    displayName: Copy Infrastructure Files
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1
    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop-infra
    - script: |
        echo "##vso[build.addbuildtag]infra"
        echo "##vso[build.addbuildtag]pipelineagents"
        echo "##vso[build.addbuildtag]$(versionSemantic)"
      displayName: Tag Build