schedules:
- cron: "0 0 * * 0"
  displayName: Sundays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    image_type: ubuntu1804
    image_readme_name: Ubuntu1804-README.md
    versionMajor: 1
    versionMinor: 0
    imageDefinitionName: 'ubuntu1804'
    pool: ContosoPool
    imageDefinitionDescription: 'Baseline image for Ubuntu 1804.'
    imageOffer: 'Industry Solutions'
    imageSku: 'Ubuntu1804Baseline'
    imageOsType: 'Linux'