
schedules:
- cron: "0 0 * * 0"
  displayName: Sunday
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    image_type: ubuntu2004
    image_readme_name: Ubuntu2004-README.md
    versionMajor: 1
    versionMinor: 0
    imageDefinitionName: 'ubuntu2004'
    pool: ContosoPool