variables:
- name: versionMajor
  value: 1
- name: versionMinor
  value: 0
  
schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    image_type: ubuntu2004
    image_readme_name: Ubuntu2004-README.md