name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-latest'

variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0
- name: publish
  value: '$[coalesce(variables.publishOverride, "1")]'

schedules:
- cron: "0 0 * * 0"
  displayName: Sundays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    imageType: ubuntu1804
    imageReadmeName: Ubuntu1804-README.md
    imageDefinitionName: 'ubuntu1804'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Ubuntu 1804'
    imageOffer: 'Industry Solutions'
    imageSku: 'Ubuntu1804Baseline'
    imageOsType: 'Linux'
    ${{ if ne(variables.publish), '1' }}:
      publish: false
    ${{ if eq(variables.publish), '1' }}:
      publish: true