name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-latest'
- name: publish
  type: boolean
  displayName: Publish to Image Gallery
  default: true 
  
variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

schedules:
- cron: "0 0 * * 6"
  displayName: Saturdays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    image_type: ubuntu2004
    image_readme_name: Ubuntu2004-README.md
    imageDefinitionName: 'ubuntu2004'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Ubuntu 2004.'
    imageOffer: 'Services Delivery'
    imageSku: 'Ubuntu2004 Product Team Baseline'
    imageOsType: 'Linux'