name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-latest'
  
variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0
- name: publish
  value: '$[coalesce(variables.publishOverride, "1")]'

schedules:
- cron: "0 0 * * 6"
  displayName: Saturdays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    imageType: ubuntu2004
    imageReadmeName: Ubuntu2004-README.md
    imageDefinitionName: 'ubuntu2004'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Ubuntu 2004.'
    imageOffer: 'Services Delivery'
    imageSku: 'Ubuntu2004 Product Team Baseline'
    imageOsType: 'Linux'
    ${{ if ne(variables.publish), '1' }}:
      publish: false
    ${{ if eq(variables.publish), '1' }}:
      publish: true