name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-latest'
- name: publish
  type: boolean
  displayName: Publish to Image Gallery
  default: true 

variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

schedules:
- cron: "0 0 * * 0"
  displayName: Sundays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    image_type: ubuntu1804
    image_readme_name: Ubuntu1804-README.md
    imageDefinitionName: 'ubuntu1804'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Ubuntu 1804'
    imageOffer: 'Industry Solutions'
    imageSku: 'Ubuntu1804Baseline'
    imageOsType: 'Linux'