name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-latest'

variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

schedules:
- cron: "0 0 * * 6"
  displayName: Saturdays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    imageType: ubuntu1804
    vmSize: Standard_D4s_v4
    imageReadmeName: Ubuntu1804-README.md
    imageDefinitionName: 'ubuntu1804'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Ubuntu 1804'
    imageOffer: 'DevOpsAgent'
    imageSku: 'Ubuntu1804HostedBaseline'
    imageOsType: 'Linux'
    publish: true