name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default: ContosoPool

variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    image_type: windows2016
    image_readme_name: Windows2016-Readme.md
    imageDefinitionName: 'windows2016'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Windows 2016.'
    imageOffer: 'Industry Solutions'
    imageSku: 'Windows2016Baseline'
    imageOsType: 'Windows'