name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default: ContosoPool
  
variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

schedules:
- cron: "0 0 * * 4"
  displayName: Thursdays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    imageType: windows2019
    imageReadmeName: Windows2019-Readme.md
    imageDefinitionName: 'windows2019'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Windows 2019.'
    imageOffer: 'Services Delivery'
    imageSku: 'Windows2019 Product Team Baseline'
    imageOsType: 'Windows'
    publish: true