name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default: ContosoPool
  
variables:
- template: templates/variables-version-semantic.yml
  parameters:
    versionMajor: 1
    versionMinor: 0

schedules:
- cron: "0 0 * * 4"
  displayName: Wednesdays
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    imageType: windows2022
    vmSize: Standard_D8s_v4
    imageReadmeName: Windows2022-Readme.md
    imageDefinitionName: 'windows2022'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Windows 2022.'
    imageOffer: 'DevOpsAgent'
    imageSku: 'Windows2022HostedBaseline'
    imageOsType: 'Windows'
    publish: true
