name: $(Build.DefinitionName)-$(versionSemantic)

parameters:
- name: pool
  type: object
  default: ContosoPool

schedules:
- cron: "0 0 * * 6"
  displayName: Saturday
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: templates/job-vmimage-generation.yml
  parameters:
    image_type: windows2019
    image_readme_name: Windows2019-Readme.md
    versionMajor: 1
    versionMinor: 0
    imageDefinitionName: 'windows2019'
    pool: ${{ parameters.pool }}
    imageDefinitionDescription: 'Baseline image for Windows 2019.'
    imageOffer: 'Industry Solutions'
    imageSku: 'Windows2019Baseline'
    imageOsType: 'Windows'