# pipeline-infra-adoagents.yml
#
# Description: 
#   Extends templates used to determin the environments used in
#   provisioning resources as well as certain governence checks 
#   such as service connection names and environment names.

parameters:
- name: sandboxSteps
  type: stepList
  default: []
- name: productionSteps
  type: stepList
  default: []

stages:
- stage: stageSandbox
  displayName: Deploying Sandbox
  variables:
  - template: /.azure/pipelines/templates/variables-config-sbx.yml
  jobs:
  - deployment: provisionInfra
    displayName: Provision Infrastructure
    environment: 'pipeline-images-sandbox'
    strategy:
      runOnce:
        deploy:
          steps:
          - ${{ each step in parameters.sandboxSteps }}:
            - ${{ step }}

- stage: stageProduction
  displayName: Deploying Production
  variables:
  - template: /.azure/pipelines/templates/variables-config-prd.yml
  dependsOn: stageSandbox
  jobs:
  - deployment: provisionInfra
    displayName: Provision Infrastructure
    environment: 'pipeline-images-production'
    variables:
      serviceConnectionName: ''
    strategy:
      runOnce:
        deploy:
          steps:
          - ${{ each step in parameters.productionSteps }}:
            - ${{ step }}