parameters:
- name: sandboxSteps
  type: stepList
  default: []
- name: productionSteps
  type: stepList
  default: []

stages:
- stage: stageSandbox
  displayName: Deploying Sandbox
  jobs:
  - deployment: provisionInfra
    displayName: Provision Infrastructure
    environment: 'pipeline-images-sandbox'
    variables:
    - template: templates/variables-infra-agents-images-sbx.yml
    strategy:
      runOnce:
        deploy:
          steps:
          - ${{ each step in parameters.sandboxSteps }}:
            - ${{ step }}

- stage: stageProduction
  displayName: Deploying Production
  jobs:
  - deployment: provisionInfra
    displayName: Provision Infrastructure
    environment: 'pipeline-images-production'
    variables:
    - template: templates/variables-infra-agents-images-prd.yml
    strategy:
      runOnce:
        deploy:
          steps:
          - ${{ each step in parameters.productionSteps }}:
            - ${{ step }}