variables:
- name: location
  value: 'eastus2'
- name: environmentType
  value: 'production'
- name: serviceConnection
  value: 'agent-image-contoso-app-sbx'
- name: agentInstallerStorageAccountName
  value: ''
- name: agentResourceGroupName
  value: ''
- name: imageResourceGroupName
  value: ''
- name: sharedImageGalleryName
  value: ''
- name: imageDefinitionName
  value: ''
- name: imageDefinitionVersion
  value: ''


  