variables:
- name: organizationName
  value: 'contoso'
- name: agentInstallerContainerName
  value: 'scriptextensions'
- name: subscription
  value: 'cbadc96b-2923-4459-bb2d-b237af7f84d6'
- name: networkSecurityGroupName
  value: 'nsg-agent'
- name: vnetName
  value: 'vnet-agent'
- name: subnetName
  value: 'snet-agen'
