variables:
- name: location
  value: 'eastus2'
- name: environmentType
  value: 'sandbox'
- name: adoEnvironment
  value: 'adoagents-sandbox'
- name: serviceConnection
  value: 'adoagent-contoso-sandbox-app'
- name: agentStorageAccountName
  value: 'stagentpasbxu63kxyluy6fd'
- name: agentResourceGroupName
  value: 'rg-pipelineagent-sandbox-u63kxyluy6fdo-agent'
- name: imageResourceGroupName
  value: 'rg-pipelineagent-sandbox-u63kxyluy6fdo-image'
- name: sharedImageGalleryName
  value: 'sig.pa.sbx.u63kxyluy6fdo'
- name: imageDefinitionName
  value: 'ubuntu2004'
- name: imageDefinitionVersion
  value: '1.0.76'