variables:
- name: location
  value: 'eastus2'
- name: environmentType
  value: 'production'
- name: adoEnvironment
  value: 'adoagents-production'
- name: serviceConnection
  value: 'adoagent-contoso-production-app'
- name: agentStorageAccountName
  value: ''
- name: agentResourceGroupName
  value: ''
- name: imageResourceGroupName
  value: ''
- name: sharedImageGalleryName
  value: ''
- name: imageDefinitionName
  value: ''
- name: imageDefinitionVersion
  value: ''