# variables-config-common.yml
#
# Description: 
#   Common configuration for multiple pipelines in this repo.

variables:

# The organization name for this workload. This is used
# in various ways like naming resources and logging.
- name: organizationName
  value: 'contoso'

# The container name used to store VM script 
# extensions while provisioning VM Agents.
- name: agentInstallerContainerName
  value: 'scriptextensions'

# The Azure subscription ID used to provisiong 
# resources. This repo currently supports a single
# subscription model. 
- name: subscription
  value: 'cbadc96b-2923-4459-bb2d-b237af7f84d6'

# Common network security name for the agents subnet.
- name: networkSecurityGroupName
  value: 'nsg-agent'

  # Common virtual network name for the agents.
- name: vnetName
  value: 'vnet-agent'

# Common subnet name for the agents. 
- name: subnetName
  value: 'snet-agent'
